"""oauth_fields_add

Revision ID: 0006
Revises: 0005
Create Date: 2026-01-10 00:05:07.440314+05:30

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, Sequence[str], None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            sa.String(length=50),
            nullable=False,
            server_default="local",
        ),
    )
    op.add_column(
        "users", sa.Column("provider_user_id", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "provider_user_id")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
