"""Add contest lifecycle status and created_by

Revision ID: 0010
Revises: 0009
Create Date: 2026-02-28 10:40:00.000000+05:30

Manual migration (not autogenerated) to:
  1. Add created_by FK column to contests.
  2. Create conteststatus enum type.
  3. Add status column (default DRAFT) to contests.
  4. Back-fill: rows with is_active=true → REGISTRATION_OPEN, rest → DRAFT.
  5. Drop is_active column.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: Union[str, Sequence[str], None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum values for the contest lifecycle state machine
conteststatus = postgresql.ENUM(
    "DRAFT",
    "REGISTRATION_OPEN",
    "ACTIVE",
    "ENDED",
    name="conteststatus",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create the conteststatus enum type
    conteststatus.create(op.get_bind(), checkfirst=True)

    # 2. Add created_by column (nullable initially so existing rows don't fail)
    op.add_column(
        "contests",
        sa.Column(
            "created_by",
            sa.String(length=36),
            nullable=True,
        ),
    )

    # 3. Populate created_by for existing rows — set to a placeholder.
    #    In production, manually update to the real admin user_id if needed.
    #    We leave NULL rows and make the column nullable for backward compat;
    #    new rows will always have created_by set via the application.
    #    (We skip NOT NULL enforcement here because existing data may lack a
    #    valid users.id to reference.)

    # 4. Add the status column (type: conteststatus enum, server default DRAFT)
    op.add_column(
        "contests",
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REGISTRATION_OPEN",
                "ACTIVE",
                "ENDED",
                name="conteststatus",
            ),
            nullable=True,  # temporarily nullable for back-fill
        ),
    )

    # 5. Back-fill: existing is_active=true → REGISTRATION_OPEN, else → DRAFT
    op.execute("""
        UPDATE contests
        SET status = CASE
            WHEN is_active = true THEN 'REGISTRATION_OPEN'::conteststatus
            ELSE 'DRAFT'::conteststatus
        END
        """)

    # 6. Now enforce NOT NULL on status
    op.alter_column("contests", "status", nullable=False)

    # 7. Add FK constraint on created_by → users.id
    op.create_foreign_key(
        "fk_contests_created_by_users",
        "contests",
        "users",
        ["created_by"],
        ["id"],
        ondelete="CASCADE",
    )

    # 8. Drop the now-replaced is_active column
    op.drop_column("contests", "is_active")


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add is_active column
    op.add_column(
        "contests",
        sa.Column("is_active", sa.Boolean(), nullable=True),
    )

    # Back-fill: REGISTRATION_OPEN & ACTIVE → True; DRAFT & ENDED → False
    op.execute("""
        UPDATE contests
        SET is_active = CASE
            WHEN status IN ('REGISTRATION_OPEN', 'ACTIVE') THEN true
            ELSE false
        END
        """)

    op.alter_column("contests", "is_active", nullable=False)

    # Drop FK and created_by
    op.drop_constraint("fk_contests_created_by_users", "contests", type_="foreignkey")
    op.drop_column("contests", "created_by")

    # Drop status column
    op.drop_column("contests", "status")

    # Drop enum type
    conteststatus.drop(op.get_bind(), checkfirst=True)
