"""is_active to team_contests

Revision ID: 0011
Revises: 0010
Create Date: 2026-03-07 12:00:23.971508+05:30

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: Union[str, Sequence[str], None] = "0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contests", "created_by", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.add_column("team_contests", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_contests", "is_active")
    op.alter_column(
        "contests", "created_by", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    # ### end Alembic commands ###
