"""Enum_update

Revision ID: 0012
Revises: 0011
Create Date: 2026-03-08 19:00:40.249082+05:30

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: Union[str, Sequence[str], None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contests", "created_by", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contests", "created_by", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    # ### end Alembic commands ###
