"""add_bidding_tables

Revision ID: 0013
Revises: 0012
Create Date: 2026-03-12 01:03:43.829497+05:30

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: Union[str, Sequence[str], None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contest_problem_assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("contest_id", sa.String(length=36), nullable=False),
        sa.Column("contest_problem_id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=False),
        sa.Column("winning_bid", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ASSIGNED", "SOLVED", "FAILED", name="assignmentstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Kolkata', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Kolkata', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["contest_problem_id"], ["contest_problems.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contest_problem_id", name="uq_assignment_contest_problem"),
    )
    op.create_index(
        "ix_assignment_contest_id",
        "contest_problem_assignments",
        ["contest_id"],
        unique=False,
    )
    op.create_index(
        "ix_assignment_team_id",
        "contest_problem_assignments",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "problem_auctions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("contest_id", sa.String(length=36), nullable=False),
        sa.Column("contest_problem_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "FINISHED", name="auctionstatus"),
            nullable=False,
        ),
        sa.Column("base_price", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("winning_team_id", sa.String(length=36), nullable=True),
        sa.Column("winning_bid", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Kolkata', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Kolkata', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["contest_problem_id"], ["contest_problems.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["winning_team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contest_problem_id", name="uq_auction_contest_problem"),
    )
    op.create_index(
        "ix_auction_contest_id", "problem_auctions", ["contest_id"], unique=False
    )
    op.create_table(
        "bids",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("auction_id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=False),
        sa.Column("bid_amount", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('Asia/Kolkata', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["auction_id"], ["problem_auctions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bid_auction_id", "bids", ["auction_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bid_auction_id", table_name="bids")
    op.drop_table("bids")
    op.drop_index("ix_auction_contest_id", table_name="problem_auctions")
    op.drop_table("problem_auctions")
    op.drop_index("ix_assignment_team_id", table_name="contest_problem_assignments")
    op.drop_index("ix_assignment_contest_id", table_name="contest_problem_assignments")
    op.drop_table("contest_problem_assignments")
    # ### end Alembic commands ###
