"""add_user_id_to_bids

Revision ID: 0014
Revises: 0013
Create Date: 2026-03-13 14:54:13.512375+05:30

"""

from typing import Sequence, Union, cast

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: Union[str, Sequence[str], None] = "0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bids", sa.Column("user_id", sa.String(length=36), nullable=True))
    op.create_foreign_key(
        None, "bids", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(cast(str, None), "bids", type_="foreignkey")
    op.drop_column("bids", "user_id")
    # ### end Alembic commands ###
