"""add_test_cases_url_to_problems

Revision ID: 0020
Revises: 0019
Create Date: 2026-03-29 09:07:43.827884+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0020'
down_revision: Union[str, Sequence[str], None] = '0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builtin_problems', sa.Column('test_cases_url', sa.String(length=1024), nullable=True))
    op.add_column('contest_problems', sa.Column('test_cases_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest_problems', 'test_cases_url')
    op.drop_column('builtin_problems', 'test_cases_url')
    # ### end Alembic commands ###
