"""Seed script: insert Two Sum as a BuiltinProblem and upload its test cases to GCS.

Run from the project root:
    python scripts/seed_two_sum.py

The script is idempotent — if the slug already exists it skips the DB insert
but still re-uploads test cases and refreshes test_cases_url.

Test cases are loaded from:
    ~/tcframe-practice/generated/two-sum_testcases.json
(generated by tcframe via `python3 scripts/generate_all.py two-sum`)
"""

import asyncio
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv
load_dotenv(ROOT / ".env")

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.core.config import settings
from app.database.models.problems import BuiltinProblem
from app.database.utils import generate_uuid
from app.services.storage import storage_service

engine = create_async_engine(settings.DB_URL, echo=False)
AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

TESTCASES_PATH = Path.home() / "tcframe-practice/generated/two-sum_testcases.json"

SLUG = "two-sum"

PROBLEM = {
    "title": "Two Sum",
    "difficulty": "easy",
    "points": 100,
    "base_price": 100,
    "time_limit_ms": 2000,
    "memory_limit_mb": 256,
    "description": (
        "Given an array of `N` integers and a target value `T`, determine if there exist "
        "two **distinct** elements in the array that sum to `T`.\n\n"
        "Output `YES` if such a pair exists, otherwise `NO`.\n\n"
        "### Input Format\n\n"
        "Line 1: Two integers `N` and `T`  \n"
        "Line 2: `N` space-separated integers\n\n"
        "### Output Format\n\n"
        "A single line: `YES` or `NO`\n\n"
        "### Examples\n\n"
        "**Input:**\n```\n5 9\n2 7 11 15 1\n```\n"
        "**Output:** `YES` (because 2 + 7 = 9)\n\n"
        "**Input:**\n```\n3 100\n1 2 3\n```\n"
        "**Output:** `NO`\n\n"
        "### Constraints\n"
        "- `2 <= N <= 10^5`\n"
        "- `-10^9 <= T <= 10^9`\n"
        "- `-10^9 <= A[i] <= 10^9`"
    ),
}


async def seed(session: AsyncSession) -> None:
    if not TESTCASES_PATH.exists():
        print(f"ERROR: Test cases file not found: {TESTCASES_PATH}")
        print("Run:  python3 ~/tcframe-practice/scripts/generate_all.py two-sum")
        sys.exit(1)

    with open(TESTCASES_PATH) as f:
        testcases = json.load(f)

    sample_count = sum(1 for t in testcases if t.get("is_sample"))
    print(f"Loaded {len(testcases)} test cases ({sample_count} sample) from {TESTCASES_PATH}")

    # ── 1. Upsert BuiltinProblem row ─────────────────────────────────────────
    existing = (await session.execute(
        select(BuiltinProblem).where(BuiltinProblem.slug == SLUG)
    )).scalar_one_or_none()

    if existing:
        print(f"  [skip insert] '{PROBLEM['title']}' already exists (id={existing.id})")
        problem = existing
    else:
        problem = BuiltinProblem(
            id=generate_uuid(),
            title=PROBLEM["title"],
            slug=SLUG,
            description=PROBLEM["description"],
            difficulty=PROBLEM["difficulty"],
            points=PROBLEM["points"],
            base_price=PROBLEM["base_price"],
            time_limit_ms=PROBLEM["time_limit_ms"],
            memory_limit_mb=PROBLEM["memory_limit_mb"],
            is_active=True,
        )
        session.add(problem)
        await session.flush()
        print(f"  [inserted] '{PROBLEM['title']}' (id={problem.id})")

    # ── 2. Upload test cases to GCS ───────────────────────────────────────────
    print(f"  Uploading to GCS...")
    url = storage_service.upload_test_cases(SLUG, testcases)
    print(f"  [uploaded] {url}")

    # ── 3. Set test_cases_url on the row ─────────────────────────────────────
    problem.test_cases_url = url
    session.add(problem)
    await session.commit()
    await session.refresh(problem)

    print(f"\nDone.")
    print(f"  Problem ID  : {problem.id}")
    print(f"  Slug        : {problem.slug}")
    print(f"  GCS URL     : {problem.test_cases_url}")
    print(f"  Test cases  : {len(testcases)} total, {sample_count} sample")


async def main() -> None:
    print(f"Seeding '{PROBLEM['title']}'...")
    async with AsyncSessionLocal() as session:
        await seed(session)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
